Single transfer task with overwrite protection
CDPHE-bioinformatics/CDPHE-SARS-CoV-2 pull request #79
Opened 2024-12-04 01:11 UTC by sam-baird

- Closes #68 
- Closes #77 
- Closes #80 

## Aim, context, and functionality 🎯

This PR refactors all workflows to call a common `transfer` task which now provides overwrite protection through the `overwrite` Boolean input variable. Workflows will fail if the `overwrite` variable is set to `false` and files already exist at the destination. If `overwite` is set to `true`, the transfer will occur even if files do not exist at the destination. This PR also needed to resolve (was blocked by) the issue duplicate version capture files (#80) since the sample-level workflows would otherwise fail if `overwrite` was set to `false`.

This PR also does some additional unrelated cleanup, such as removing the obsolete SC2_illumina_se_assembly.wdl and SC2_multifasta_lineage_calling.wdl workflows and their associated scripts/docs. Also updating inputs / outputs for many workflows in the docs since many were out-of-date.

## Workflow Changes ✅

### Upstream Effects

Input JSONs need to be changed with overwrite set to `false` by default (to prevent accidental overwrites), except for novel mutations `overwrite_historical` should be set to `true`.

### Input Changes

The new common `transfer` task takes in a `SubdirsToFiles` struct that contains an `Array[Pair[String, Array[File?]]]` which maps destination subdirectories to input files. The task also takes the `overwrite` boolean, which is now provided with new workflow input(s) for all workflows. 

### Output Changes

For sample-level workflows (the assembly workflows) the `version_capture` task will now output a separate file for each sample with an additional `sample_name` column and transfer to the `version_capture` folder instead of the `summary_results` folder. SC2_illumina_pe_assembly.wdl will now output the scrubbed FASTQ files to `fastq_scrubbed` folder instead of `scrubbed_fastq` to be consistent with the SC2_ont_assembly.wdl.

### Downstream Effects

I don't think BigQuery ingests the version capture CSVs yet so these changes should be backwards compatible with BigQuery.

The clinical submissions repo needs to be updated to revert CDPHE-bioinformatics/SARS-CoV-2-clinical-submissions#52 (see issue CDPHE-bioinformatics/SARS-CoV-2-clinical-submissions#62)

## Testing 🛠️

Test results and input data tables stored on GCP at `validation/CDPHE-SARS-CoV-2/sb-transfer-overwrite`

**Test dataset(s):**

cov_2218_grid
covwwt_0369_nextseq
covwwt_0370_nextseq

**Test(s) performed:**

- Tested cov_2218_grid SC2_ont_assembly.wdl (miniwdl and Terra) and SC2_lineage_calling_and_results.wdl (Terra) with `overwrite` set true and false and made sure transfer task behavior was consistent with the setting of the `overwrite` variable and presence/absence of files at the destination. Checked files went to correct locations.

- Performed similar tests as above for covwwt_0369_nextseq on Terra for SC2_illumina_pe_assembly.wdl and SC2_lineage_calling_and_results.wdl

- SC2_novel_mutations.wdl was tested with covwwt_0370_nextseq (inputs / outputs were changed to not interfere production results -- stored at `validation/CDPHE-SARS-CoV-2/sb-transfer-overwrite/novel_mutations`.

**Results (including if the results matched the expected results):**

Results matched expected results.

## Developer Checklist 👷‍♀️

- [x] Prior to development, issues were discussed with the bioinformatics team members and approved
- [x] Code has been refactored to sufficiently address the issues this pull request closes
- [x] Testing was performed and the results from testing match the expected results
- [x] All code changes match our style guide
- [x] README has been updated to reflect changes
- [ ] Workflow diagrams in READMEs have been updated to reflect changes

## Reviewer Checklist 🔍

- [ ] Met with developer to review all changes and testing performed
- [x] Code refactoring sufficiently address the issue(s) that this pull request closes
- [x] All code meets style guide critera
- [x] Confirm testing was sufficient (e.g. correct dataset was used for testing, results match the expected results). If not, the developer will perform additional testing which should be documented in the testing section above.
- [ ] New version release number has been decided upon (if applicable)

2024-12-19 19:26 UTC, molly-hetheringtonrauth requested changes
review and reply to comments prior to merging.

2024-12-19 22:15 UTC, molly-hetheringtonrauth commented on workflows/SC2_novel_mutations.wdl
@arianna-smith - can you review the changes made to this WDL to ensure that everything looks ok to you?

2024-12-19 23:39 UTC, sam-baird commented on tasks/version_capture_task.wdl
It is a nice convention provided by the WDL spec to handle substituting optional variables
https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#prepending-a-string-to-an-optional-parameter

2024-12-19 23:41 UTC, sam-baird commented on docs/wastewater_workflow.md
`overwrite_project_and_set` and `overwrite_historical` are both new to this PR. The historical mutations file should typically be overwitten to add the new mutations, but the project- and set-level files should typically not be overwritten.

2024-12-20 19:42 UTC, sam-baird commented
I've updated the output locations for version capture files and nextclade per our discussions

2025-01-03 21:51 UTC, sam-baird commented on workflows/SC2_novel_mutations.wdl
@arianna-smith The `transfer` task accepts `File?` rather than `File`, so the the task will not fail if one of the files does not exist. I tested this in the assembly workflows for example, the transfer will not fail `fastq_scrubbed` does not exist (when `scrub_fastq= false`).

2025-01-15 20:34 UTC, merged